BEGIN TRANSACTION;
CREATE TABLE games (
               name text, 
               description text, 
               price text, 
               developers text, 
               publishers text, 
               date_release text, 
               genres text
               );
INSERT INTO "games" VALUES('Counter-Strike 2','For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.','Free','Valve','Valve','21 Aug, 2012','Экшены');
INSERT INTO "games" VALUES('Dota 2','Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And no matter if it''s their 10th hour of play or 1,000th, there''s always something new to discover. With regular updates that ensure a constant evolution of gameplay, features, and heroes, Dota 2 has taken on a life of its own.','Free','Valve','Valve','Jul 9, 2013','Action');
INSERT INTO "games" VALUES('PUBG: BATTLEGROUNDS','Play PUBG: BATTLEGROUNDS for free. Land on strategic locations, loot weapons and supplies, and survive to become the last team standing across various, diverse Battlegrounds. Squad up and join the Battlegrounds for the original Battle Royale experience that only PUBG: BATTLEGROUNDS can offer.','Free','PUBG Corporation','KRAFTON, Inc.','21 Dec, 2017','Action');
INSERT INTO "games" VALUES('Marvel Rivals','Marvel Rivals is a Super Hero Team-Based PVP Shooter! Assemble an all-star Marvel squad, devise countless strategies by combining powers to form unique Team-Up skills and fight in destructible, ever-changing battlefields across the continually evolving Marvel universe!','Free','NetEase Games','NetEase Games','Dec 5, 2024','Action');
INSERT INTO "games" VALUES('Path of Exile 2','Path of Exile 2 is a next generation Action RPG from Grinding Gear Games, featuring co-op for up to six players. Set years after the original Path of Exile, you will return to the dark world of Wraeclast and seek to end the corruption that is spreading.','27,75€','Grinding Gear Games','Grinding Gear Games','6 Dec, 2024','Action');
INSERT INTO "games" VALUES('Banana','Banana is a clicker Game, in which you click a Banana! In Banana you click the Banana to gain even more Bananas! Every 3 hours, you get dropped a banana. Each banana is also made by the community in discord. Come hang out with us and let''s grow into something awesome !','Free','Sky','Sky','Apr 23, 2024','Adventure');
INSERT INTO "games" VALUES('Grand Theft Auto V','Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Santos and Blaine County in resolutions of up to 4k and beyond, as well as the chance to experience the game running at 60 frames per second.','price not available','Rockstar North','Rockstar Games','Apr 13, 2015','Action');
INSERT INTO "games" VALUES('NARAKA: BLADEPOINT','Dive into the legends of the Far East in NARAKA: BLADEPOINT; team up with friends in fast-paced melee fights for a Battle Royale experience unlike any other. Find your playstyle with a varied cast of heroes with unique skills. More than 20 million players have already joined the fray, play free now!','Free','24 Entertainment','NetEase Games Global','Aug 11, 2021','Action');
INSERT INTO "games" VALUES('Rust','The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife, other inhabitants, the environment, and other survivors. Do whatever it takes to last another night.','$39.99','Facepunch Studios','Facepunch Studios','Feb 8, 2018','Action');
INSERT INTO "games" VALUES('Wallpaper Engine','Use stunning live wallpapers on your desktop. Animate your own images to create new wallpapers or import videos/websites and share them on the Steam Workshop!','$4.99','Wallpaper Engine Team','Wallpaper Engine Team','Nov 16, 2018','Casual');
INSERT INTO "games" VALUES('Delta Force','Delta Force is back! The iconic series returns as the definitive free-to-play modern team-based tactical shooter and featuring three distinct gameplay modes: large-scale PvP warfare, intense extraction shooter action, and a remake of the legendary Black Hawk Down campaign.','Free','Team Jade','TiMi Studio Group','Dec 4, 2024','Action');
INSERT INTO "games" VALUES('Apex Legends™','Apex Legends is the award-winning, free-to-play Hero Shooter from Respawn Entertainment. Master an ever-growing roster of legendary characters with powerful abilities, and experience strategic squad play and innovative gameplay in the next evolution of Hero Shooter and Battle Royale.','Free','Respawn','Electronic Arts','Nov 4, 2020','Action');
INSERT INTO "games" VALUES('Palworld','Fight, farm, build and work alongside mysterious creatures called &quot;Pals&quot; in this completely new multiplayer, open world survival and crafting game!','$29.99','Pocketpair','Pocketpair','Jan 18, 2024','Action');
INSERT INTO "games" VALUES('Stardew Valley','You''ve inherited your grandfather''s old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?','$14.99','ConcernedApe','ConcernedApe','Feb 26, 2016','Indie');
INSERT INTO "games" VALUES('War Thunder','War Thunder is the most comprehensive free-to-play, cross-platform, MMO military game dedicated to aviation, armoured vehicles, and naval craft, from the early 20th century to the most advanced modern combat units. Join now and take part in major battles on land, in the air, and at sea.','Free','Gaijin Entertainment','Gaijin Network Ltd','Aug 15, 2013','Action');
INSERT INTO "games" VALUES('EA SPORTS FC™ 25','EA SPORTS FC™ 25 gives you more ways to win for the club. Team up with friends in your favourite modes with the new 5v5 Rush, and manage your club to victory as FC IQ delivers more tactical control than ever before.','Rp 319 600','EA Canada & EA Romania','Electronic Arts','26 Sep, 2024','Simulation');
INSERT INTO "games" VALUES('Tom Clancy''s Rainbow Six® Siege','Tom Clancy''s Rainbow Six® Siege is an elite, tactical team-based shooter where superior planning and execution triumph.','$7.99','Ubisoft Montreal','Ubisoft','Dec 1, 2015','Action');
INSERT INTO "games" VALUES('Football Manager 2024','Build a world-class team ready to dominate your rivals in football’s most prestigious competitions. Progress never stops when you’re pursuing footballing greatness.','$59.99','Sports Interactive','SEGA','Nov 6, 2023','Simulation');
INSERT INTO "games" VALUES('Baldur''s Gate 3','Baldur’s Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons &amp; Dragons, where your choices shape a tale of fellowship and betrayal, survival and sacrifice, and the lure of absolute power.','$59.99','Larian Studios','Larian Studios','Aug 3, 2023','Avontuur');
INSERT INTO "games" VALUES('Sid Meier’s Civilization® VI','Civilization VI is the newest installment in the award winning Civilization Franchise. Expand your empire, advance your culture and go head-to-head against history’s greatest leaders. Will your civilization stand the test of time?','$59.99','Firaxis Games','2K','Oct 20, 2016','Strategy');
INSERT INTO "games" VALUES('Crosshair X','Overlay custom crosshairs on every game you play. Choose from thousands of unique crosshairs created by the Crosshair X community or design your own using the designer.','$8.99','CenterPoint Gaming','CenterPoint Gaming','Aug 17, 2020','Action');
INSERT INTO "games" VALUES('Hearts of Iron IV','Victory is at your fingertips! Your ability to lead your nation is your supreme weapon, the strategy game Hearts of Iron IV lets you take command of any nation in World War II; the most engaging conflict in world history.','167,70 kr','Paradox Development Studio','Paradox Interactive','6 Jun, 2016','Simulation');
INSERT INTO "games" VALUES('Warframe','Awaken as an unstoppable warrior and battle alongside your friends in this story-driven free-to-play online action game','Free','Digital Extremes','Digital Extremes','Mar 25, 2013','Action');
INSERT INTO "games" VALUES('ELDEN RING','THE CRITICALLY ACCLAIMED FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.','¥ 298.00','FromSoftware, Inc.','FromSoftware, Inc.','24 Feb, 2022','Action');
INSERT INTO "games" VALUES('Call of Duty®','The Call of Duty® experience supports Call of Duty®: Black Ops 6, Call of Duty®: Modern Warfare® III, Call of Duty®: Modern Warfare® II and Call of Duty®: Warzone™.','price not available','Treyarch','Activision','Oct 27, 2022','Action');
INSERT INTO "games" VALUES('Team Fortress 2','Nine distinct classes provide a broad range of tactical abilities and personalities. Constantly updated with new game modes, maps, equipment and, most importantly, hats!','Free','Valve','Valve','Oct 10, 2007','Action');
INSERT INTO "games" VALUES('Euro Truck Simulator 2','Travel across Europe as king of the road, a trucker who delivers important cargo across impressive distances! With dozens of cities to explore, your endurance, skill and speed will all be pushed to their limits.','$19.99','SCS Software','SCS Software','Oct 12, 2012','Indie');
INSERT INTO "games" VALUES('DayZ','How long can you survive a post-apocalyptic world? A land overrun with an infected &quot;zombie&quot; population, where you compete with other survivors for limited resources. Will you team up with strangers and stay strong together? Or play as a lone wolf to avoid betrayal? This is DayZ – this is your story.','$49.99','Bohemia Interactive','Bohemia Interactive','Dec 13, 2018','Action');
INSERT INTO "games" VALUES('DYNASTY WARRIORS: ORIGINS','Become immersed in exhilarating battles as a nameless hero in the Three Kingdoms','$69.99','KOEI TECMO GAMES CO., LTD.','KOEI TECMO GAMES CO., LTD.','Jan 16, 2025','Action');
INSERT INTO "games" VALUES('Black Myth: Wukong','Black Myth: Wukong is an action RPG rooted in Chinese mythology. You shall set out as the Destined One to venture into the challenges and marvels ahead, to uncover the obscured truth beneath the veil of a glorious legend from the past.','$59.99','Game Science','Game Science','Aug 19, 2024','Экшены');
INSERT INTO "games" VALUES('Once Human','Once Human is a multiplayer open-world survival game set in a strange, post-apocalyptic future. Unite with friends to fight monstrous enemies, uncover secret plots, compete for resources, and build your own territory. Once, you were merely human. Now, you have the power to remake the world.','Free','Starry Studio','Starry Studio','Jul 9, 2024','Action');
INSERT INTO "games" VALUES('The Elder Scrolls V: Skyrim Special Edition','Winner of more than 200 Game of the Year Awards, The Elder Scrolls V: Skyrim Special Edition brings the epic fantasy to life in stunning detail. The Special Edition includes the critically acclaimed game and add-ons with all-new features.','$39.99','Bethesda Game Studios','Bethesda Softworks','Oct 27, 2016','RPG');
INSERT INTO "games" VALUES('Don''t Starve Together','Fight, Farm, Build and Explore Together in the standalone multiplayer expansion to the uncompromising wilderness survival game, Don''t Starve.','14,99€','Klei Entertainment','Klei Entertainment','21 Apr, 2016','Actie');
INSERT INTO "games" VALUES('VRChat','Join our growing community as you explore, play, and help craft the future of social VR. Create worlds and custom avatars. Welcome to VRChat.','Free','VRChat Inc.','VRChat Inc.','Feb 1, 2017','Adventure');
INSERT INTO "games" VALUES('Project Zomboid','Project Zomboid is the ultimate in zombie survival. Alone or in MP: you loot, build, craft, fight, farm and fish in a struggle to survive. A hardcore RPG skillset, a vast map, massively customisable sandbox and a cute tutorial raccoon await the unwary. So how will you die? All it takes is a bite..','$19.99','The Indie Stone','The Indie Stone','Nov 8, 2013','Indie');
INSERT INTO "games" VALUES('Monster Hunter: World','Welcome to a new world! In Monster Hunter: World, the latest installment in the series, you can enjoy the ultimate hunting experience, using everything at your disposal to hunt monsters in a new world teeming with surprises and excitement.','₩ 34,800','CAPCOM Co., Ltd.','CAPCOM Co., Ltd.','8 Aug, 2018','Action');
INSERT INTO "games" VALUES('tModLoader','Dig, Fight, and Build your way through the world of player-created mods on Terraria with tModLoader - this DLC makes modding Terraria a reality!','Free','TML Team','Re-Logic','May 16, 2020','Action');
INSERT INTO "games" VALUES('Crab Game','Crab Game is a First-Person Multiplayer game where you play through several different minigames based on children''s games, until only one player stands victorious.','Free','Dani','Dani','Oct 29, 2021','Action');
INSERT INTO "games" VALUES('Limbus Company','As the Executive Manager of Limbus Company, lead your group of twelve Sinners, venture into the buried facilities of Lobotomy Corporation, and lay claim on the Golden Boughs.','Free','ProjectMoon','ProjectMoon','Feb 26, 2023','Action');
INSERT INTO "games" VALUES('The Binding of Isaac: Rebirth','The Binding of Isaac: Rebirth is a randomly generated action RPG shooter with heavy Rogue-like elements. Following Isaac on his journey players will find bizarre treasures that change Isaac’s form giving him super human abilities and enabling him to fight off droves of mysterious creatures, discover secrets and fight his way to safety.','$14.99','Nicalis, Inc.','Nicalis, Inc.','Nov 4, 2014','Action');
INSERT INTO "games" VALUES('Red Dead Redemption 2','Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, RDR2 is the epic tale of outlaw Arthur Morgan and the infamous Van der Linde gang, on the run across America at the dawn of the modern age. Also includes access to the shared living world of Red Dead Online.','CDN$ 79.99','Rockstar Games','Rockstar Games','5 Dec, 2019','Action');
INSERT INTO "games" VALUES('The Sims™ 4','Play with life and discover the possibilities. Unleash your imagination and create a world of Sims that’s wholly unique. Explore and customize every detail from Sims to homes–and much more.','Free','Maxis','Electronic Arts','Jun 18, 2020','Adventure');
INSERT INTO "games" VALUES('Dead by Daylight','Trapped forever in a realm of eldritch evil where even death is not an escape, four determined Survivors face a bloodthirsty Killer in a vicious game of nerve and wits. Pick a side and step into a world of tension and terror with horror gaming''s best asymmetrical multiplayer.','$19.99','Behaviour Interactive Inc.','Behaviour Interactive Inc.','Jun 14, 2016','Action');
INSERT INTO "games" VALUES('ARK: Survival Evolved','Stranded on the shores of a mysterious island, you must learn to survive. Use your cunning to kill or tame the primeval creatures roaming the land, and encounter other players to survive, dominate... and escape!','$14.99','Studio Wildcard','Studio Wildcard','Aug 27, 2017','Action');
INSERT INTO "games" VALUES('HELLDIVERS™ 2','The Galaxy’s Last Line of Offence. Enlist in the Helldivers and join the fight for freedom across a hostile galaxy in a fast, frantic, and ferocious third-person shooter.','$39.99','Arrowhead Game Studios','PlayStation Publishing LLC','Feb 8, 2024','Action');
INSERT INTO "games" VALUES('Terraria','Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. Four Pack also available!','$9.99','Re-Logic','Re-Logic','May 16, 2011','Action');
INSERT INTO "games" VALUES('PAYDAY 2','PAYDAY 2 is an action-packed, four-player co-op shooter that once again lets gamers don the masks of the original PAYDAY crew - Dallas, Hoxton, Wolf and Chains - as they descend on Washington DC for an epic crime spree.','$2.49','OVERKILL - a Starbreeze Studio.','Starbreeze Publishing AB','Aug 13, 2013','Action');
INSERT INTO "games" VALUES('Cyberpunk 2077','Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and ceaseless body modification.','$59.99','CD PROJEKT RED','CD PROJEKT RED','Dec 9, 2020','RPG');
INSERT INTO "games" VALUES('7 Days to Die','7 Days to Die is an open-world game that is a unique combination of first-person shooter, survival horror, tower defense, and role-playing games. Play the definitive zombie survival sandbox RPG that came first. Navezgane awaits!','$44.99','The Fun Pimps','The Fun Pimps Entertainment LLC','Jul 25, 2024','Action');
INSERT INTO "games" VALUES('Lost Ark','Embark on an odyssey for the Lost Ark in a vast, vibrant world: explore new lands, seek out lost treasures, and test yourself in thrilling action combat in this action-packed free-to-play RPG.','Free','Smilegate RPG','Amazon Games','Feb 11, 2022','Action');
INSERT INTO "games" VALUES('Mount & Blade II: Bannerlord','A strategy/action RPG. Create a character, engage in diplomacy, craft, trade and conquer new lands in a vast medieval sandbox. Raise armies to lead into battle and command and fight alongside your troops in massive real-time battles using a deep but intuitive skill-based combat system.','$49.99','TaleWorlds Entertainment','TaleWorlds Entertainment','Oct 25, 2022','Action');
INSERT INTO "games" VALUES('Left 4 Dead 2','Set in the zombie apocalypse, Left 4 Dead 2 (L4D2) is the highly anticipated sequel to the award-winning Left 4 Dead, the #1 co-op game of 2008. This co-operative action horror FPS takes you and your friends through the cities, swamps and cemeteries of the Deep South, from Savannah to New Orleans across five expansive campaigns.','$9.99','Valve','Valve','Nov 16, 2009','Action');
INSERT INTO "games" VALUES('Farming Simulator 25','Farming Simulator 25 invites you to join the rewarding farm life, single-handedly or cooperatively in multiplayer. This Farm is Your Farm!','$49.99','Giants Software','Giants Software','Nov 12, 2024','Simulation');
INSERT INTO "games" VALUES('Garry''s Mod','Garry''s Mod is a physics sandbox. There aren''t any predefined aims or goals. We give you the tools and leave you to play.','$4.99','Facepunch Studios','Valve','Nov 29, 2006','Casual');
INSERT INTO "games" VALUES('Balatro','The poker roguelike. Balatro is a hypnotically satisfying deckbuilder where you play illegal poker hands, discover game-changing jokers, and trigger adrenaline-pumping, outrageous combos.','¥ 1,700','LocalThunk','Playstack','20 Feb, 2024','Casual');
INSERT INTO "games" VALUES('Overwatch® 2','Overwatch 2 is a critically acclaimed, team-based shooter game set in an optimistic future with an evolving roster of heroes. Team up with friends and jump in today.','Free','Blizzard Entertainment, Inc.','Blizzard Entertainment, Inc.','Aug 10, 2023','Action');
INSERT INTO "games" VALUES('RimWorld','A sci-fi colony sim driven by an intelligent AI storyteller. Generates stories by simulating psychology, ecology, gunplay, melee combat, climate, biomes, diplomacy, interpersonal relationships, art, medicine, trade, and more.','$34.99','Ludeon Studios','Ludeon Studios','Oct 17, 2018','Indie');
INSERT INTO "games" VALUES('NBA 2K25','Command every court with authenticity and realism Powered by ProPLAY™, giving you ultimate control over how you play in NBA 2K25. Define your legacy in MyCAREER, MyTEAM, MyNBA, and The W.','$69.99','Visual Concepts','2K','Oct 28, 2024','Simulation');
INSERT INTO "games" VALUES('Total War: WARHAMMER III','The cataclysmic conclusion to the Total War: WARHAMMER trilogy is here. Rally your forces and step into the Realm of Chaos, a dimension of mind-bending horror where the very fate of the world will be decided. Will you conquer your Daemons… or command them?','$59.99','CREATIVE ASSEMBLY','SEGA','Feb 16, 2022','Action');
INSERT INTO "games" VALUES('The Witcher 3: Wild Hunt','You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy, a living weapon that can alter the shape of the world.','$39.99','CD PROJEKT RED','CD PROJEKT RED','May 18, 2015','RPG');
INSERT INTO "games" VALUES('Diablo® IV','Join the fight for Sanctuary in Diablo® IV, the ultimate action RPG adventure. Experience the critically acclaimed campaign and new seasonal content.','CDN$ 66.99','Blizzard Entertainment, Inc.','Blizzard Entertainment, Inc.','17 Oct, 2023','Action');
INSERT INTO "games" VALUES('Valheim','A brutal exploration and survival game for 1-10 players, set in a procedurally-generated purgatory inspired by viking culture. Battle, build, and conquer your way to a saga worthy of Odin’s patronage!','$19.99','Iron Gate AB','Coffee Stain Publishing','Feb 2, 2021','Action');
INSERT INTO "games" VALUES('Factorio','Factorio is a game about building and creating automated factories to produce items of increasing complexity, within an infinite 2D world. Use your imagination to design your factory, combine simple elements into ingenious structures, and finally protect it from the creatures who don''t really like you.','$35.00','Wube Software LTD.','Wube Software LTD.','Aug 14, 2020','Casual');
INSERT INTO "games" VALUES('ARK: Survival Ascended','ARK is reimagined from the ground-up into the next-generation of video game technology with Unreal Engine 5! Form a tribe, tame &amp; breed hundreds of unique dinosaurs and primeval creatures, explore, craft, build, and fight your way to the top of the food-chain. Your new world awaits!','$44.99','Studio Wildcard','Studio Wildcard','Oct 25, 2023','Action');
INSERT INTO "games" VALUES('Lethal Company','A co-op horror about scavenging at abandoned moons to sell scrap to the Company.','₩ 11,000','Zeekerss','Zeekerss','23 Oct, 2023','Action');
INSERT INTO "games" VALUES('Street Fighter™ 6','Here comes Capcom’s newest challenger! Street Fighter™ 6 launches worldwide on June 2nd, 2023 and represents the next evolution of the Street Fighter™ series! Street Fighter 6 spans three distinct game modes, including World Tour, Fighting Ground and Battle Hub.','59,99€','CAPCOM Co., Ltd.','CAPCOM Co., Ltd.','1 Jun, 2023','Action');
INSERT INTO "games" VALUES('BeamNG.drive','A dynamic soft-body physics vehicle simulator capable of doing just about anything.','$24.99','BeamNG','BeamNG','May 29, 2015','Racing');
INSERT INTO "games" VALUES('Crusader Kings III','Love, fight, scheme, and claim greatness. Determine your noble house’s legacy in the sprawling grand strategy of Crusader Kings III. Death is only the beginning as you guide your dynasty’s bloodline in the rich and larger-than-life simulation of the Middle Ages.','CDN$ 20.09','Paradox Development Studio','Paradox Interactive','1 Sep, 2020','RPG');
INSERT INTO "games" VALUES('STALCRAFT: X','STALCRAFT: X is the largest online game set in the open world of the Chernobyl Exclusion Zone. Dive into this universe, filled with mutants and anomalies alone or with friends — unforgettable experiences are guaranteed!','Free','EXBO','EXBO','Dec 9, 2022','Action');
INSERT INTO "games" VALUES('It Takes Two','Embark on the craziest journey of your life in It Takes Two. Invite a friend to join for free with Friend’s Pass and work together across a huge variety of gleefully disruptive gameplay challenges. Winner of GAME OF THE YEAR at the Game Awards 2021.','$39.99','Hazelight Studios','Electronic Arts','Mar 25, 2021','Action');
INSERT INTO "games" VALUES('Hunt: Showdown 1896','Hunt: Showdown 1896 is a new era of the addictively unforgiving extraction shooter. In corrupted backwaters lost to history, fight back alone – or with friends – against timeless evil. Twisted monsters and other ruthless Hunters stand between you and your Bounty. Risk everything as Hunt consumes you','$29.99','Crytek','Crytek','Aug 27, 2019','Action');
INSERT INTO "games" VALUES('Age of Empires II: Definitive Edition','42 Civilizations, 229 Campaign Missions, Singleplayer, Co-Op, Multiplayer, In-Game Editor, Mods, Cross-play...It is good to be the king.','$12.24','Forgotten Empires','Xbox Game Studios','Nov 14, 2019','Strategy');
INSERT INTO "games" VALUES('FINAL FANTASY VII REBIRTH','Неведомые странствия продолжаются... Выбравшись из города Мидгар, Клауд и его друзья отправляются в путешествие по планете. Новые приключения ждут вас во второй части трилогии обновленной FINAL FANTASY VII!','19 600₸','Square Enix','Square Enix','23 янв. 2025 г.','Экшены');
INSERT INTO "games" VALUES('Goose Goose Duck','Goose Goose Duck is a game of social deduction for up to 16 players. Players are separated into different groups that are each assigned a different objective. Complete your team’s objective to win!','Free','Gaggle Studios, Inc.','Gaggle Studios, Inc.','Oct 3, 2021','Casual');
INSERT INTO "games" VALUES('Stellaris','Explore a galaxy full of wonders in this sci-fi grand strategy game from Paradox Development Studios. Interact with diverse alien races, discover strange new worlds with unexpected events and expand the reach of your empire. Each new adventure holds almost limitless possibilities.','$9.99','Paradox Development Studio','Paradox Interactive','May 9, 2016','Simulation');
INSERT INTO "games" VALUES('Governor of Poker 3','Governor of Poker 3 is the best multiplayer poker game with a great design. In this multi-player version of Governor of Poker you compete live with thousands of real poker players to prove you are the number 1 Texas Hold ’em poker star!','Free','Playtika Ltd.','Playtika Ltd.','Feb 19, 2016','Casual');
INSERT INTO "games" VALUES('Europa Universalis IV','Rule your land and dominate the world with unparalleled freedom, depth and historical accuracy. Write a new history of the world and build an empire for the ages.','55,90 kr','Paradox Development Studio','Paradox Interactive','13 Aug, 2013','Simulation');
INSERT INTO "games" VALUES('Forza Horizon 5','Explore the vibrant open world landscapes of Mexico with limitless, fun driving action in the world’s greatest cars. Join a thrilling game of chase with our new 5v1 Multiplayer Experience: Hide &amp; Seek.','$29.99','Playground Games','Xbox Game Studios','Nov 8, 2021','Action');
INSERT INTO "games" VALUES('Destiny 2','Destiny 2 is an action MMO with a single evolving world that you and your friends can join anytime, anywhere, absolutely free.','Free','Bungie','Bungie','Oct 1, 2019','Action');
INSERT INTO "games" VALUES('SCUM','Traverse punishing environments, looting, crafting and evading the constant threats to your life. The unprecedented levels of character customization and progression are your ultimate tools for survival.','$39.99','Gamepires','Jagex Ltd','Aug 29, 2018','Action');
INSERT INTO "games" VALUES('MIR4','MIR4 is a free-to-play open world K-fantasy MMORPG that can be cross-played on both PC and mobile devices. MIR4 is full of action and features numerous large scale clan PVP battles. Join now and become a legend.','Free','Wemade Next','Wemade','Aug 25, 2021','Action');
INSERT INTO "games" VALUES('Yu-Gi-Oh! Master Duel','Yu-Gi-Oh! MASTER DUEL is the ultimate free-to-play cross-platform strategy card game with fast-paced Duels, stunning HD graphics and a new, dynamic soundtrack! Get ready to challenge Duelists around the world!','Free','KONAMI','KONAMI','18 Jan, 2022','Simulation');
INSERT INTO "games" VALUES('The Forest','As the lone survivor of a passenger jet crash, you find yourself in a mysterious forest battling to stay alive against a society of cannibalistic mutants. Build, explore, survive in this terrifying first person survival horror simulator.','₩ 20,500','Endnight Games Ltd','Endnight Games Ltd','30 Apr, 2018','Action');
INSERT INTO "games" VALUES('OBS Studio','Free and open-source software for video recording and live streaming','Free','OBS Project','OBS Project','Mar 21, 2022','Utilities');
INSERT INTO "games" VALUES('Soundpad','Play sounds in voice chats in high digital quality. Add sounds or music to your microphone signal so others will hear it, too.','$4.99','Leppsoft','Leppsoft','Sep 30, 2017','Audio Production');
INSERT INTO "games" VALUES('Squad','Squad is a tactical FPS that provides authentic combat experiences through teamwork, communication, and realistic combat. It bridges the gap between arcade shooter and military realism with 100-player battles, combined-arms warfare, and base building.','$49.99','Offworld','Offworld','Sep 23, 2020','Action');
INSERT INTO "games" VALUES('Phasmophobia','Phasmophobia is a 4 player online co-op psychological horror. Paranormal activity is on the rise and it’s up to you and your team to use all the ghost-hunting equipment at your disposal in order to gather as much evidence as you can.','$19.99','Kinetic Games','Kinetic Games','Sep 18, 2020','Action');
INSERT INTO "games" VALUES('Satisfactory','Satisfactory is a first-person open-world factory building game with a dash of exploration and combat. Play alone or with friends, explore an alien planet, create multi-story factories, and enter conveyor belt heaven!','$39.99','Coffee Stain Studios','Coffee Stain Publishing','Sep 10, 2024','Adventure');
INSERT INTO "games" VALUES('Rocket League®','Rocket League is a high-powered hybrid of arcade-style soccer and vehicular mayhem with easy-to-understand controls and fluid, physics-driven competition. Rocket League includes casual and competitive Online Matches, a fully-featured offline Season Mode, special “Mutators” that let you change the rules entirely, hockey and...','price not available','Psyonix LLC','Psyonix LLC','Jul 6, 2015','Action');
INSERT INTO "games" VALUES('Counter-Strike','Play the world''s number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team''s success. Your team''s success affects your role.','$9.99','Valve','Valve','Nov 1, 2000','Action');
INSERT INTO "games" VALUES('Black Desert','Played by over 20 million Adventurers - Black Desert Online is an open-world, action MMORPG. Experience intense, action-packed combat, battle massive world bosses, fight alongside friends to siege and conquer castles, and train in professions such as fishing, trading, crafting, cooking, and more!','$9.99','Pearl Abyss','Pearl Abyss','May 24, 2017','Action');
INSERT INTO "games" VALUES('Russian Fishing 4','Russian Fishing 4 is a fishing simulator with RPG elements. There is no story line and the whole process is based on the concept of an open, free to roam and free to play game.','Free','FishSoft LLC','FishSoft LLC','Nov 10, 2021','Adventure');
INSERT INTO "games" VALUES('Sons Of The Forest','Sent to find a missing billionaire on a remote island, you find yourself in a cannibal-infested hellscape. Craft, build, and struggle to survive, alone or with friends, in this terrifying new open-world survival horror simulator.','$29.99','Endnight Games Ltd','Newnight ','Feb 22, 2024','Action');
INSERT INTO "games" VALUES('eFootball™','The feverish football game with a worldwide total of 750 million downloads is waiting for you! Play eFootball™ with users around the world!','Free','KONAMI','KONAMI','Sep 29, 2021','Simulation');
INSERT INTO "games" VALUES('Slay the Spire','We fused card games and roguelikes together to make the best single player deckbuilder we could. Craft a unique deck, encounter bizarre creatures, discover relics of immense power, and Slay the Spire!','$8.49','Mega Crit','Mega Crit','Jan 23, 2019','Indie');
INSERT INTO "games" VALUES('Geometry Dash','Jump and fly your way through danger in this rhythm-based action platformer!','$4.99','RobTop Games','RobTop Games','Dec 22, 2014','Action');
INSERT INTO "games" VALUES('Eternal Return','Eternal Return is a free-to-play, 2.5D perspective Battle Royale game. Search, Craft, Hunt, and Fight using a variety of characters. Plan your strategy and become the last survivor on this eternal experiment.','Free','Nimble Neuron','Nimble Neuron','19 Jul, 2023','Indie');
INSERT INTO "games" VALUES('Unturned','You''re a survivor in the zombie infested ruins of society, and must work with your friends and forge alliances to remain among the living.','Free','Smartly Dressed Games','Smartly Dressed Games','Jul 7, 2017','Action');
INSERT INTO "games" VALUES('Sid Meier''s Civilization® V','Create, discover, and download new player-created maps, scenarios, interfaces, and more!','$29.99','Firaxis Games','2K','Sep 21, 2010','Strategy');
INSERT INTO "games" VALUES('VTube Studio','VTube Studio is all you''ll ever need to become a Live2D VTuber, with innovative features such as pinning props to your model and many more still to come.','Free','DenchiSoft','DenchiSoft','Mar 12, 2021','Indie');
CREATE TABLE reviews (
               playtime int, 
               past_two_week_playtimes int, 
               reviews text);
COMMIT;
